---

destination: ./.cache/prod/

# URL Settings
url: 'https://mylesbraithwaite.com'
baseurl: ''
upload_url: 'https://mylesbraithwaite.com/uploads'
onion_url: 'http://tdm76lx3jweaozkd.onion'

# Contact Form
raven_key: '902c9b4a-b8d0-11e6-8826-34363bd0c9bc'
recaptcha_sitekey: '6Lf8-ygTAAAAAKWdLY5sYOgduRZo7mjTPHwhAVp3'

# Jekyll-Assets Settings
assets:
  baseurl: 'https://mylesbraithwaite.com/assets/'

# Piwik Settings
piwik:
  baseurl: 'piwik.mylesb.ca'
  site_id: '18'
  set_domains: '*.mylesbraithwaite.com'

# Google Analytics Settings
google_analytics_tacking_code: 'UA-1642439-2'

# Search Engine Settings
google_verify: wXrllbKtdZfN1RaZfZW8K3ZPq0Iaf0LEP91x7DteBqI
bing_verify: A46832B420EF0C2C771BA8538C0B2B38
yandex_verify: 80d31d8e9c5e56d9

# webmention Settings
pingback: https://webmention.io/mylesbraithwaite.com/xmlrpc
webmention: https://webmention.io/mylesbraithwaite.com/webmention

# rsync Settings
rsync: myles@bear.mylesbraithwaite.com:/srv/www/mylesbraithwaite.com/www/html/
