---

destination: ./.cache/prod/

# URL Settings
url: 'https://mylesbraithwaite.com'
baseurl: ''
upload_url: 'https://mylesbraithwaite.com/uploads'
onion_url: 'http://tdm76lx3jweaozkd.onion'

# Contact Form
raven_key: '902c9b4a-b8d0-11e6-8826-34363bd0c9bc'
recaptcha_sitekey: '6Lf8-ygTAAAAAKWdLY5sYOgduRZo7mjTPHwhAVp3'

# Jekyll-Assets Settings
assets:
  baseurl: 'https://mylesbraithwaite.com/assets/'

# Piwik Settings
piwik:
  baseurl: 'piwik.mylesb.ca'
  site_id: '18'
  set_domains: '*.mylesbraithwaite.com'

# Google Analytics Settings
google_analytics_tacking_code: 'UA-1642439-2'

# rsync Settings
rsync: myles@bear.mylesbraithwaite.com:/srv/www/mylesbraithwaite.com/www/html/
