#!/bin/sh

if ! [ -f `which bundle` ];
then
  echo 'bundler is required';
fi

if ! [ -f `which python2.7` ];
then
  echo 'Python==2.7 is requried'
fi

if ! [ -f `which virtualenv` ];
then
  echo 'virtualenv is required'
fi

if ! [ -f `which bower` ];
then
  echo 'bower is required';
fi

bundle install --path=vendor/bundle/
bower install
virtualenv --python=python2.7 vendor/virtualenv
./vendor/virtualenv/bin/pip install --requirments=requirments.txt
