#!/bin/sh

if ! [ -f `which bundle` ];
then
  echo 'bundler is required';
fi

if ! [ -f `which fab` ];
then
  echo 'fabric is required';
fi

if ! [ -f `which bower` ];
then
  echo 'bower is required';
fi

bundle install
bower install
